// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.1
// source: gitlab.dg.ru/ocb/product-creation/validation-service/api/validation/validation.proto

package validation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attributes           []*Product_Attribute `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Barcode              string               `protobuf:"bytes,5,opt,name=barcode,proto3" json:"barcode,omitempty"`
	Vat                  int64                `protobuf:"varint,6,opt,name=vat,proto3" json:"vat,omitempty"`
	Price                int64                `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Images               []*Product_Image     `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	Depth                int64                `protobuf:"varint,9,opt,name=depth,proto3" json:"depth,omitempty"`
	Weight               int64                `protobuf:"varint,10,opt,name=weight,proto3" json:"weight,omitempty"`
	Height               int64                `protobuf:"varint,11,opt,name=height,proto3" json:"height,omitempty"`
	Width                int64                `protobuf:"varint,12,opt,name=width,proto3" json:"width,omitempty"`
	CommercialCategoryId int64                `protobuf:"varint,13,opt,name=commercial_category_id,json=commercialCategoryId,proto3" json:"commercial_category_id,omitempty"`
}

func (x *Product) Reset() {
	*x = Product{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetAttributes() []*Product_Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Product) GetVat() int64 {
	if x != nil {
		return x.Vat
	}
	return 0
}

func (x *Product) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetImages() []*Product_Image {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetDepth() int64 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Product) GetWeight() int64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Product) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Product) GetWidth() int64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Product) GetCommercialCategoryId() int64 {
	if x != nil {
		return x.CommercialCategoryId
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId   string          `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Fulfillment int64           `protobuf:"varint,2,opt,name=fulfillment,proto3" json:"fulfillment,omitempty"`
	Errors      []*Result_Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Result) GetFulfillment() int64 {
	if x != nil {
		return x.Fulfillment
	}
	return 0
}

func (x *Result) GetErrors() []*Result_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ValidateProductsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Products []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
}

func (x *ValidateProductsRequest) Reset() {
	*x = ValidateProductsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProductsRequest) ProtoMessage() {}

func (x *ValidateProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProductsRequest.ProtoReflect.Descriptor instead.
func (*ValidateProductsRequest) Descriptor() ([]byte, []int) {
	return file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateProductsRequest) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type ValidateProductsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*Result `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *ValidateProductsResponse) Reset() {
	*x = ValidateProductsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidateProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateProductsResponse) ProtoMessage() {}

func (x *ValidateProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateProductsResponse.ProtoReflect.Descriptor instead.
func (*ValidateProductsResponse) Descriptor() ([]byte, []int) {
	return file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateProductsResponse) GetResult() []*Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type Product_Attribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ComplexId int64                      `protobuf:"varint,3,opt,name=complex_id,json=complexId,proto3" json:"complex_id,omitempty"`
	Values    []*Product_Attribute_Value `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *Product_Attribute) Reset() {
	*x = Product_Attribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product_Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product_Attribute) ProtoMessage() {}

func (x *Product_Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product_Attribute.ProtoReflect.Descriptor instead.
func (*Product_Attribute) Descriptor() ([]byte, []int) {
	return file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Product_Attribute) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product_Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product_Attribute) GetComplexId() int64 {
	if x != nil {
		return x.ComplexId
	}
	return 0
}

func (x *Product_Attribute) GetValues() []*Product_Attribute_Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Product_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	IsMain bool   `protobuf:"varint,2,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
}

func (x *Product_Image) Reset() {
	*x = Product_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product_Image) ProtoMessage() {}

func (x *Product_Image) ProtoReflect() protoreflect.Message {
	mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product_Image.ProtoReflect.Descriptor instead.
func (*Product_Image) Descriptor() ([]byte, []int) {
	return file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Product_Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Product_Image) GetIsMain() bool {
	if x != nil {
		return x.IsMain
	}
	return false
}

type Product_Attribute_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Product_Attribute_Value) Reset() {
	*x = Product_Attribute_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Product_Attribute_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product_Attribute_Value) ProtoMessage() {}

func (x *Product_Attribute_Value) ProtoReflect() protoreflect.Message {
	mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product_Attribute_Value.ProtoReflect.Descriptor instead.
func (*Product_Attribute_Value) Descriptor() ([]byte, []int) {
	return file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Product_Attribute_Value) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product_Attribute_Value) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Result_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attribute   string `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Result_Error) Reset() {
	*x = Result_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result_Error) ProtoMessage() {}

func (x *Result_Error) ProtoReflect() protoreflect.Message {
	mi := &file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result_Error.ProtoReflect.Descriptor instead.
func (*Result_Error) Descriptor() ([]byte, []int) {
	return file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Result_Error) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *Result_Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto protoreflect.FileDescriptor

var file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDesc = []byte{
	0x0a, 0x56, 0x67, 0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x72, 0x75,
	0x2f, 0x6f, 0x63, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2d, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x38, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x6f,
	0x63, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x22, 0x90, 0x06, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x6b,
	0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x4b, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x6f, 0x63, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x52,
	0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x72, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x76,
	0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x61, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x5f, 0x0a, 0x06, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x18, 0x08, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x47, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x6f, 0x63, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x64, 0x65, 0x70, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68,
	0x12, 0x34, 0x0a, 0x16, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x72, 0x63, 0x69, 0x61, 0x6c, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x1a, 0xe8, 0x01, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x78, 0x49, 0x64, 0x12, 0x69, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x51, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x6f,
	0x63, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x1a, 0x2d, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x1a, 0x32, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x4d, 0x61, 0x69, 0x6e, 0x22, 0xf2, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x66, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6c, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x5e, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x46, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x6f, 0x63, 0x62, 0x2e, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x1a, 0x47, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x74,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x78, 0x0a, 0x17, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5d, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x6f,
	0x63, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x73, 0x22, 0x74, 0x0a, 0x18, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x58, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x40, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x6f, 0x63, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0xcb, 0x01, 0x0a, 0x0b, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41, 0x50, 0x49, 0x12, 0xbb, 0x01, 0x0a, 0x10, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x12,
	0x51, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x6f, 0x63, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x52, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x6f, 0x63, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x6b, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x47, 0x5a, 0x45, 0x67, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x2e, 0x72, 0x75, 0x2f, 0x6f, 0x63, 0x62, 0x2f, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescOnce sync.Once
	file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescData = file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDesc
)

func file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescGZIP() []byte {
	file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescOnce.Do(func() {
		file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescData = protoimpl.X.CompressGZIP(file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescData)
	})
	return file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDescData
}

var file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_goTypes = []interface{}{
	(*Product)(nil),                  // 0: dg.ocb.product_creation.validation_service.pkg.product.Product
	(*Result)(nil),                   // 1: dg.ocb.product_creation.validation_service.pkg.product.Result
	(*ValidateProductsRequest)(nil),  // 2: dg.ocb.product_creation.validation_service.pkg.product.ValidateProductsRequest
	(*ValidateProductsResponse)(nil), // 3: dg.ocb.product_creation.validation_service.pkg.product.ValidateProductsResponse
	(*Product_Attribute)(nil),        // 4: dg.ocb.product_creation.validation_service.pkg.product.Product.Attribute
	(*Product_Image)(nil),            // 5: dg.ocb.product_creation.validation_service.pkg.product.Product.Image
	(*Product_Attribute_Value)(nil),  // 6: dg.ocb.product_creation.validation_service.pkg.product.Product.Attribute.Value
	(*Result_Error)(nil),             // 7: dg.ocb.product_creation.validation_service.pkg.product.Result.Error
}
var file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_depIdxs = []int32{
	4, // 0: dg.ocb.product_creation.validation_service.pkg.product.Product.attributes:type_name -> dg.ocb.product_creation.validation_service.pkg.product.Product.Attribute
	5, // 1: dg.ocb.product_creation.validation_service.pkg.product.Product.images:type_name -> dg.ocb.product_creation.validation_service.pkg.product.Product.Image
	7, // 2: dg.ocb.product_creation.validation_service.pkg.product.Result.errors:type_name -> dg.ocb.product_creation.validation_service.pkg.product.Result.Error
	0, // 3: dg.ocb.product_creation.validation_service.pkg.product.ValidateProductsRequest.products:type_name -> dg.ocb.product_creation.validation_service.pkg.product.Product
	1, // 4: dg.ocb.product_creation.validation_service.pkg.product.ValidateProductsResponse.result:type_name -> dg.ocb.product_creation.validation_service.pkg.product.Result
	6, // 5: dg.ocb.product_creation.validation_service.pkg.product.Product.Attribute.values:type_name -> dg.ocb.product_creation.validation_service.pkg.product.Product.Attribute.Value
	2, // 6: dg.ocb.product_creation.validation_service.pkg.product.ValidateAPI.ValidateProducts:input_type -> dg.ocb.product_creation.validation_service.pkg.product.ValidateProductsRequest
	3, // 7: dg.ocb.product_creation.validation_service.pkg.product.ValidateAPI.ValidateProducts:output_type -> dg.ocb.product_creation.validation_service.pkg.product.ValidateProductsResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() {
	file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_init()
}
func file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_init() {
	if File_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateProductsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidateProductsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product_Attribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Product_Attribute_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_goTypes,
		DependencyIndexes: file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_depIdxs,
		MessageInfos:      file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_msgTypes,
	}.Build()
	File_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto = out.File
	file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_rawDesc = nil
	file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_goTypes = nil
	file_gitlab_dg_ru_ocb_product_creation_validation_service_api_validation_validation_proto_depIdxs = nil
}
