// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// KafkaProducer is an autogenerated mock type for the KafkaProducer type
type KafkaProducer struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: ctx, topic, key, message
func (_m *KafkaProducer) SendMessage(ctx context.Context, topic string, key string, message string) error {
	ret := _m.Called(ctx, topic, key, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, topic, key, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendProtoMessageHash provides a mock function with given fields: ctx, topic, key, value
func (_m *KafkaProducer) SendProtoMessageHash(ctx context.Context, topic string, key int, value protoreflect.ProtoMessage) error {
	ret := _m.Called(ctx, topic, key, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, protoreflect.ProtoMessage) error); ok {
		r0 = rf(ctx, topic, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
