// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	images "gitlab.dg.ru/ocb/product-creation/product-storage-api/internal/pb/storage-api/api/images"
)

// ImageStorageAPIServer is an autogenerated mock type for the ImageStorageAPIServer type
type ImageStorageAPIServer struct {
	mock.Mock
}

// ProcessImage provides a mock function with given fields: _a0, _a1
func (_m *ImageStorageAPIServer) ProcessImage(_a0 context.Context, _a1 *images.Image) (*images.ImageResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *images.ImageResponse
	if rf, ok := ret.Get(0).(func(context.Context, *images.Image) *images.ImageResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*images.ImageResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *images.Image) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedImageStorageAPIServer provides a mock function with given fields:
func (_m *ImageStorageAPIServer) mustEmbedUnimplementedImageStorageAPIServer() {
	_m.Called()
}
