// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "gitlab.dg.ru/ocb/product-creation/product-storage-api/internal/pb/seller-api/api/category/v1"
)

// CategoryAPIServer is an autogenerated mock type for the CategoryAPIServer type
type CategoryAPIServer struct {
	mock.Mock
}

// GetCategoryTree provides a mock function with given fields: _a0, _a1
func (_m *CategoryAPIServer) GetCategoryTree(_a0 context.Context, _a1 *v1.GetCategoryTreeRequest) (*v1.GetCategoryTreeResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *v1.GetCategoryTreeResponse
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetCategoryTreeRequest) *v1.GetCategoryTreeResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.GetCategoryTreeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.GetCategoryTreeRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedCategoryAPIServer provides a mock function with given fields:
func (_m *CategoryAPIServer) mustEmbedUnimplementedCategoryAPIServer() {
	_m.Called()
}
