// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v1 "gitlab.dg.ru/ocb/product-creation/product-storage-api/internal/pb/seller-api/api/category/v1"
)

// CategoryAPIClient is an autogenerated mock type for the CategoryAPIClient type
type CategoryAPIClient struct {
	mock.Mock
}

// GetCategoryTree provides a mock function with given fields: ctx, in, opts
func (_m *CategoryAPIClient) GetCategoryTree(ctx context.Context, in *v1.GetCategoryTreeRequest, opts ...grpc.CallOption) (*v1.GetCategoryTreeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.GetCategoryTreeResponse
	if rf, ok := ret.Get(0).(func(context.Context, *v1.GetCategoryTreeRequest, ...grpc.CallOption) *v1.GetCategoryTreeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.GetCategoryTreeResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *v1.GetCategoryTreeRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
