// Code generated by "scratch generate config". DO NOT EDIT.

package config

import (
	"context"

	realtimeconfig "gitlab.dg.ru/platform/realtime-config-go"
	"gitlab.dg.ru/platform/scratch/app"
	"gitlab.dg.ru/platform/scratch/config"
	"gitlab.dg.ru/platform/tracer-go/logger"
)

type configKey string

// Strictly-typed config keys.
// Keys are parsed from values.yaml "realtimeconfig" section and values_production.yaml "deploy.env" section.
const (
	// Log level enum
	LogLevel                  = configKey("log_level")
	BrandList                 = configKey("brand_list")
	CategoriesApiGateway      = configKey("categories_api_gateway")
	CompetitorApiGateway      = configKey("competitor_api_gateway")
	ImageStorageApiGateway    = configKey("image_storage_api_gateway")
	ImageWorkersCount         = configKey("image_workers_count")
	KafkaBrokerList           = configKey("kafka_broker_list")
	KafkaCorrectTopic         = configKey("kafka_correct_topic")
	KafkaCreateTopic          = configKey("kafka_create_topic")
	KafkaFillTopic            = configKey("kafka_fill_topic")
	KafkaGroupSuffix          = configKey("kafka_group_suffix")
	KafkaMetricsTopic         = configKey("kafka_metrics_topic")
	OgrnList                  = configKey("ogrn_list")
	PgConnIdle                = configKey("pg_conn_idle")
	PgConnLimit               = configKey("pg_conn_limit")
	ProductBatchSize          = configKey("product_batch_size")
	ProductServiceMetaGateway = configKey("product_service_meta_gateway")
	ShardConfig               = configKey("shard_config")
	ValidationApiGateway      = configKey("validation_api_gateway")
)

const (
	// AppName is parsed from .gitlab-ci.yml SERVICE_NAME variable
	AppName = "ocb-product-storage-api"

	// AppNS is parsed from .gitlab-ci.yml K8S_NAMESPACE variable
	// or if K8S_NAMESPACE has ENV $variable it is parsed from project module name 'gitlab.dg.ru/<ns>/<project>'
	AppNS = "ocb"
)

func init() {
	app.SetName(AppName)
	app.SetNamespace(AppNS)
}

// GetValue returns realtimeconfig.Value for a given strictly-typed configKey.
//
// If you want to mock the client, use scratch/config.SetClient() function. Restriction - you won't be able to use T.Parallel().
// Use NewClient() instead, to be more flexible in mocking.
func GetValue(ctx context.Context, key configKey) realtimeconfig.Value {
	return getValue(config.Client(), ctx, key)
}

// Client is a simple facade for realtimeconfig.Client.
//
// Use it directly for more flexible mocking of realtimeconfig.Client.
// See comments for config.GetValue() func.
type Client struct {
	client realtimeconfig.Client
}

// NewClient returns new Client instance.
func NewClient(c realtimeconfig.Client) *Client {
	return &Client{client: c}
}

// GetValue returns realtimeconfig.Value for a given strictly-typed configKey.
func (c *Client) GetValue(ctx context.Context, key configKey) realtimeconfig.Value {
	return getValue(c.client, ctx, key)
}

func getValue(client realtimeconfig.Client, ctx context.Context, key configKey) realtimeconfig.Value {
	v, err := client.Value(ctx, string(key))
	if err == nil {
		return v
	}

	switch err {
	case realtimeconfig.ErrVariableNotFound:
		logger.Warnf(ctx, "%#q config variable not found!", key)
	default:
		logger.Errorf(ctx, "unexpected get %#q config error: %s", key, err)
	}
	return realtimeconfig.NewNilValue(err)
}
